export const CareersData = [
  {
    id: 1,
    title:
      " Public Notice for Re-Scheduling of Written Examination for the posts of Upper Division Clerk (BPS-11) and Assistant (BPS-15) Under The Pakistan Post Office Department ",
    url: "https://pakpost.gov.pk/images/2023-03-17-Public-Notice-For-Re-Scheduling-of-Written-Examination-of-UDC-Asstt.jpg",
    title2: "",
    url2: "",
    title3: "",
    url3: "",
    title4: "",
    url4: "",
    title5: "",
    url5: "",
    title6: "",
    url6: "",
  },
  {
    id: 2,
    title:
      " Public Notice for Recruitment on ASPOS/ AS (MST) in Direct Quota Under The Pakistan Post Office Department ",
    url: "https://pakpost.gov.pk/images/2023-02-03-Public-Notice-For-Recruitment-of-ASPOS-MST-Examination-Schedule.pdf",
    title2: "",
    url2: "",
    title3: "",
    url3: "",
    title4: "",
    url4: "",
    title5: "",
    url5: "",
    title6: "",
    url6: "",
  },
  {
    id: 3,
    title:
      " Corrigendum of Advertisement for Appointment on Vacant Vacancies of BPS 1-15 of the Pakistan Post % ADDG (Estt) Directorate General Pakistan Post Islamabad ",
    url: "https://pakpost.gov.pk/images/2022-11-15-Corrigendum-advertisement-clarification.pdf",
    title2: "",
    url2: "",
    title3: "",
    url3: "",
    title4: "",
    url4: "",
    title5: "",
    url5: "",
    title6: "",
    url6: "",
  },
];
