export const TendersData = [
  {
    id: 1,
    title: "Tender Notice for the purchase/ supply of Tablets/Mobile Handsets",
    url: "https://ep.gov.pk/Tender_Notice/Tender%20Notice-Mobile%20Phones.pdf",
    title2: "",
    url2: "",
    title3: "",
    url3: "",
    title4: "",
    url4: "",
    title5: "",
    url5: "",
    title6: "",
    url6: "",
  },
  {
    id: 2,
    title:
      "Tender Notice of Private Partner for Delivery of Urgent Mail Service Plus (UMS-Plus) Under The Directorate General Pakistan Post Office, Islamabad",
    url: "https://ep.gov.pk/Tender_Notice/UMS%20Plus/2022-05-20-Tender-Document-of-Private-Partner-For-Delivery-Of-UMS-PLUS-Under-The-DGPPO-IBD.pdf",
    title2: "Tender Documents",
    url2: "https://ep.gov.pk/Tender_Notice/UMS%20Plus/UMS%20Plus%20Tender.jpeg",
    title3: "",
    url3: "",
    title4: "",
    url4: "",
    title5: "",
    url5: "",
    title6: "",
    url6: "",
  },
  {
    id: 3,
    title: "Tender Document for Selection of Airlines & Transport Partners",
    url: "https://ep.gov.pk/Tender_Notice/Tender%20Document%20for%20Selection%20of%20Airlines%20&%20Transport%20Partners.pdf",
    title2: "",
    url2: "",
    title3: "",
    url3: "",
    title4: "",
    url4: "",
    title5: "",
    url5: "",
    title6: "",
    url6: "",
  },
  {
    id: 4,
    title:
      "Tender Notice for Procurement of State-of-the-Art ICT Digital Platform Under The Directorate General Pakistan Post Office Islamabad Opening Date 09-03-2022",
    url: "https://ep.gov.pk/Tender_Notice/2022-01-21-Tender-Notice-for-State-of-the-Art-Under-The-Directorate-General-Pakistan-Post-Office-Islamabad.jpg",
    title2: "REVISED TENDER DOCUMENTS",
    url2: "https://ep.gov.pk/Tender_Notice/2022-02-22-Revised-Tender-Documents-for-State-of-the-Art-Under-The-Directorate-General-Pakistan-Post-Office-Islamabad.pdf",
    title3: "Corrigendum",
    url3: "https://ep.gov.pk/Tender_Notice/2022-02-18-Corrigendum-Tender-Notice-for-State-of-the-Art-Under-The-Directorate-General-Pakistan-Post-Office-Ibd.jpg",
    title4: "",
    url4: "",
    title5: "",
    url5: "",
    title6: "",
    url6: "",
  },
  {
    id: 5,
    title:
      "Tender Notice For Selection Of Transportor/ Delivery Partners For EMS-PLUS Under The Directorate General Pakistan Post Office Islamabad",
    url: "https://ep.gov.pk/Tender_Notice/Tender_Notice.html",
    title2: "TENDER DOCUMENT",
    url2: "https://ep.gov.pk/Document_Tender_Notice_For_Selection.pdf",
    title3: "M/S DHL Pakistan (Pvt) Limited",
    url3: "https://ep.gov.pk/Tender_Notice/dhl.pdf",
    title4:
      "M/S Gerry's International (Pvt) Limited, a licensee of Federal Express Corporation",
    url4: "https://ep.gov.pk/Tender_Notice/fedex.pdf",
    title5:
      "M/S Universal Logistics (Pvt) Limited, an Authorized service contractor of UPS",
    url5: "https://ep.gov.pk/Tender_Notice/ULS.pdf",
    title6: "M/S Focus Technologies (Pvt) Limited",
    url6: "https://ep.gov.pk/Tender_Notice/Focus.pdf",
  },
  {
    id: 6,
    title:
      "Baseline Contract Awarded to M/S 360 Technologies (Pvt) Ltd. regarding EMTTS, IPS, MDUS and CMS to Director General, Pakistan Post Islamabad",
    url: "https://ep.gov.pk/2021-07-29.pdf",
    title2: "",
    url2: "",
    title3: "",
    url3: "",
    title4: "",
    url4: "",
    title5: "",
    url5: "",
    title6: "",
    url6: "",
  },
  {
    id: 7,
    title: "Contract Awards Proforma - I and II",
    url: "https://ep.gov.pk/2021-09-06.pdf",
    title2: "",
    url2: "",
    title3: "",
    url3: "",
    title4: "",
    url4: "",
    title5: "",
    url5: "",
    title6: "",
    url6: "",
  },
];

export const NewsData = [
  {
    id: 1,
    title:
      "Public Notice for Recruitment on ASPOS/ AS (MST) in Direct Quota Under The Pakistan Post Office Department",
    url: "https://ep.gov.pk/files/2023-02-03-Public-Notice-For-Recruitment-of-ASPOS-MST-Examination-Schedule.pdf",
  },
  {
    id: 2,
    title: "Same Day Delivery In Twin Cities (Rawalpindi - Islamabad)",
    url: "https://ep.gov.pk/services/same_day_delivery.asp",
  },
  {
    id: 3,
    title:
      "51st International Letter-Writing Competition For Young People (2022)",
    url: "https://ep.gov.pk/files/51st%20International%20Letter%20Writing%20Competition%20For%20Young%20People%20(2022).jpg",
  },
];
